//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace TechSupportService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public partial class LoginResult : object
    {
        
        private string FullNameField;
        
        private TechSupportService.DataContract.Role RoleField;
        
        private bool ValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TechSupportService.DataContract.Role Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valid
        {
            get
            {
                return this.ValidField;
            }
            set
            {
                this.ValidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public partial class WorkerData : object
    {
        
        private string AddressField;
        
        private string EmailField;
        
        private string FullNameField;
        
        private int IDField;
        
        private string PhoneField;
        
        private string ProfilePictureField;
        
        private TechSupportService.DataContract.Role RoleField;
        
        private TechSupportService.Status StatusField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture
        {
            get
            {
                return this.ProfilePictureField;
            }
            set
            {
                this.ProfilePictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TechSupportService.DataContract.Role Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TechSupportService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public enum Status : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Away = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolvedQuestion", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public partial class SolvedQuestion : object
    {
        
        private string AnswerField;
        
        private string CategoryField;
        
        private int CustomerIDField;
        
        private int IDField;
        
        private string[] KeyWordsField;
        
        private string QuestionField;
        
        private System.DateTime TimeAnsweredField;
        
        private System.DateTime TimeAskedField;
        
        private string TopicField;
        
        private int WorkerIDField;
        
        private string WorkerNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] KeyWords
        {
            get
            {
                return this.KeyWordsField;
            }
            set
            {
                this.KeyWordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAnswered
        {
            get
            {
                return this.TimeAnsweredField;
            }
            set
            {
                this.TimeAnsweredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAsked
        {
            get
            {
                return this.TimeAskedField;
            }
            set
            {
                this.TimeAskedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic
        {
            get
            {
                return this.TopicField;
            }
            set
            {
                this.TopicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerID
        {
            get
            {
                return this.WorkerIDField;
            }
            set
            {
                this.WorkerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerName
        {
            get
            {
                return this.WorkerNameField;
            }
            set
            {
                this.WorkerNameField = value;
            }
        }
    }
}
namespace TechSupportService.DataContract
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public enum Role : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HelpDesk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technician = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boss = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public partial class CustomerData : object
    {
        
        private string EmailField;
        
        private string FullNameField;
        
        private int IDField;
        
        private string PhoneField;
        
        private string PictureField;
        
        private int PointsField;
        
        private System.DateTime RegTimeField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture
        {
            get
            {
                return this.PictureField;
            }
            set
            {
                this.PictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegTime
        {
            get
            {
                return this.RegTimeField;
            }
            set
            {
                this.RegTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewTechWork", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public partial class NewTechWork : object
    {
        
        private string AddressField;
        
        private string CustomerNameField;
        
        private int IDField;
        
        private int TechIDField;
        
        private System.DateTime TimeOrderedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TechID
        {
            get
            {
                return this.TechIDField;
            }
            set
            {
                this.TechIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeOrdered
        {
            get
            {
                return this.TimeOrderedField;
            }
            set
            {
                this.TimeOrderedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public partial class Message : object
    {
        
        private string MessagField;
        
        private string SenderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messag
        {
            get
            {
                return this.MessagField;
            }
            set
            {
                this.MessagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITechSupportService1")]
public interface ITechSupportService1
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/TechnicianLogin", ReplyAction="http://tempuri.org/ITechSupportService1/TechnicianLoginResponse")]
    System.IAsyncResult BeginTechnicianLogin(string username, string passWD, System.AsyncCallback callback, object asyncState);
    
    TechSupportService.LoginResult EndTechnicianLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/HelpDeskWorkerList", ReplyAction="http://tempuri.org/ITechSupportService1/HelpDeskWorkerListResponse")]
    System.IAsyncResult BeginHelpDeskWorkerList(System.AsyncCallback callback, object asyncState);
    
    TechSupportService.WorkerData[] EndHelpDeskWorkerList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/CustomerList", ReplyAction="http://tempuri.org/ITechSupportService1/CustomerListResponse")]
    System.IAsyncResult BeginCustomerList(System.AsyncCallback callback, object asyncState);
    
    TechSupportService.DataContract.CustomerData[] EndCustomerList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/GetMyNewTechworks", ReplyAction="http://tempuri.org/ITechSupportService1/GetMyNewTechworksResponse")]
    System.IAsyncResult BeginGetMyNewTechworks(string username, System.AsyncCallback callback, object asyncState);
    
    TechSupportService.DataContract.NewTechWork[] EndGetMyNewTechworks(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/UploadSolvedQuestion", ReplyAction="http://tempuri.org/ITechSupportService1/UploadSolvedQuestionResponse")]
    System.IAsyncResult BeginUploadSolvedQuestion(TechSupportService.SolvedQuestion question, System.AsyncCallback callback, object asyncState);
    
    void EndUploadSolvedQuestion(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/UserLogin", ReplyAction="http://tempuri.org/ITechSupportService1/UserLoginResponse")]
    System.IAsyncResult BeginUserLogin(string username, string password, System.AsyncCallback callback, object asyncState);
    
    bool EndUserLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/GetProfilePicture", ReplyAction="http://tempuri.org/ITechSupportService1/GetProfilePictureResponse")]
    System.IAsyncResult BeginGetProfilePicture(string username, System.AsyncCallback callback, object asyncState);
    
    string EndGetProfilePicture(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/GetUserProfilePicture", ReplyAction="http://tempuri.org/ITechSupportService1/GetUserProfilePictureResponse")]
    System.IAsyncResult BeginGetUserProfilePicture(string username, System.AsyncCallback callback, object asyncState);
    
    string EndGetUserProfilePicture(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/RegisterNewUser")]
    System.IAsyncResult BeginRegisterNewUser(string fullName, string email, string userName, string password, string profilePicture, System.AsyncCallback callback, object asyncState);
    
    void EndRegisterNewUser(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/SendMessageToSupport")]
    System.IAsyncResult BeginSendMessageToSupport(string username, string sender, string message, System.AsyncCallback callback, object asyncState);
    
    void EndSendMessageToSupport(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITechSupportService1/GetMyMessages", ReplyAction="http://tempuri.org/ITechSupportService1/GetMyMessagesResponse")]
    System.IAsyncResult BeginGetMyMessages(string username, System.AsyncCallback callback, object asyncState);
    
    TechSupportService.DataContract.Message[] EndGetMyMessages(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITechSupportService1Channel : ITechSupportService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TechnicianLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public TechnicianLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TechSupportService.LoginResult Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TechSupportService.LoginResult)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HelpDeskWorkerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public HelpDeskWorkerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TechSupportService.WorkerData[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TechSupportService.WorkerData[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public CustomerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TechSupportService.DataContract.CustomerData[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TechSupportService.DataContract.CustomerData[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetMyNewTechworksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetMyNewTechworksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TechSupportService.DataContract.NewTechWork[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TechSupportService.DataContract.NewTechWork[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public UserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetProfilePictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetProfilePictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetUserProfilePictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetUserProfilePictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetMyMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetMyMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public TechSupportService.DataContract.Message[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((TechSupportService.DataContract.Message[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TechSupportService1Client : System.ServiceModel.ClientBase<ITechSupportService1>, ITechSupportService1
{
    
    private BeginOperationDelegate onBeginTechnicianLoginDelegate;
    
    private EndOperationDelegate onEndTechnicianLoginDelegate;
    
    private System.Threading.SendOrPostCallback onTechnicianLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginHelpDeskWorkerListDelegate;
    
    private EndOperationDelegate onEndHelpDeskWorkerListDelegate;
    
    private System.Threading.SendOrPostCallback onHelpDeskWorkerListCompletedDelegate;
    
    private BeginOperationDelegate onBeginCustomerListDelegate;
    
    private EndOperationDelegate onEndCustomerListDelegate;
    
    private System.Threading.SendOrPostCallback onCustomerListCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetMyNewTechworksDelegate;
    
    private EndOperationDelegate onEndGetMyNewTechworksDelegate;
    
    private System.Threading.SendOrPostCallback onGetMyNewTechworksCompletedDelegate;
    
    private BeginOperationDelegate onBeginUploadSolvedQuestionDelegate;
    
    private EndOperationDelegate onEndUploadSolvedQuestionDelegate;
    
    private System.Threading.SendOrPostCallback onUploadSolvedQuestionCompletedDelegate;
    
    private BeginOperationDelegate onBeginUserLoginDelegate;
    
    private EndOperationDelegate onEndUserLoginDelegate;
    
    private System.Threading.SendOrPostCallback onUserLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetProfilePictureDelegate;
    
    private EndOperationDelegate onEndGetProfilePictureDelegate;
    
    private System.Threading.SendOrPostCallback onGetProfilePictureCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetUserProfilePictureDelegate;
    
    private EndOperationDelegate onEndGetUserProfilePictureDelegate;
    
    private System.Threading.SendOrPostCallback onGetUserProfilePictureCompletedDelegate;
    
    private BeginOperationDelegate onBeginRegisterNewUserDelegate;
    
    private EndOperationDelegate onEndRegisterNewUserDelegate;
    
    private System.Threading.SendOrPostCallback onRegisterNewUserCompletedDelegate;
    
    private BeginOperationDelegate onBeginSendMessageToSupportDelegate;
    
    private EndOperationDelegate onEndSendMessageToSupportDelegate;
    
    private System.Threading.SendOrPostCallback onSendMessageToSupportCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetMyMessagesDelegate;
    
    private EndOperationDelegate onEndGetMyMessagesDelegate;
    
    private System.Threading.SendOrPostCallback onGetMyMessagesCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public TechSupportService1Client()
    {
    }
    
    public TechSupportService1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TechSupportService1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TechSupportService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TechSupportService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<TechnicianLoginCompletedEventArgs> TechnicianLoginCompleted;
    
    public event System.EventHandler<HelpDeskWorkerListCompletedEventArgs> HelpDeskWorkerListCompleted;
    
    public event System.EventHandler<CustomerListCompletedEventArgs> CustomerListCompleted;
    
    public event System.EventHandler<GetMyNewTechworksCompletedEventArgs> GetMyNewTechworksCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadSolvedQuestionCompleted;
    
    public event System.EventHandler<UserLoginCompletedEventArgs> UserLoginCompleted;
    
    public event System.EventHandler<GetProfilePictureCompletedEventArgs> GetProfilePictureCompleted;
    
    public event System.EventHandler<GetUserProfilePictureCompletedEventArgs> GetUserProfilePictureCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RegisterNewUserCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendMessageToSupportCompleted;
    
    public event System.EventHandler<GetMyMessagesCompletedEventArgs> GetMyMessagesCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginTechnicianLogin(string username, string passWD, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginTechnicianLogin(username, passWD, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TechSupportService.LoginResult ITechSupportService1.EndTechnicianLogin(System.IAsyncResult result)
    {
        return base.Channel.EndTechnicianLogin(result);
    }
    
    private System.IAsyncResult OnBeginTechnicianLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        string passWD = ((string)(inValues[1]));
        return ((ITechSupportService1)(this)).BeginTechnicianLogin(username, passWD, callback, asyncState);
    }
    
    private object[] OnEndTechnicianLogin(System.IAsyncResult result)
    {
        TechSupportService.LoginResult retVal = ((ITechSupportService1)(this)).EndTechnicianLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnTechnicianLoginCompleted(object state)
    {
        if ((this.TechnicianLoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.TechnicianLoginCompleted(this, new TechnicianLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void TechnicianLoginAsync(string username, string passWD)
    {
        this.TechnicianLoginAsync(username, passWD, null);
    }
    
    public void TechnicianLoginAsync(string username, string passWD, object userState)
    {
        if ((this.onBeginTechnicianLoginDelegate == null))
        {
            this.onBeginTechnicianLoginDelegate = new BeginOperationDelegate(this.OnBeginTechnicianLogin);
        }
        if ((this.onEndTechnicianLoginDelegate == null))
        {
            this.onEndTechnicianLoginDelegate = new EndOperationDelegate(this.OnEndTechnicianLogin);
        }
        if ((this.onTechnicianLoginCompletedDelegate == null))
        {
            this.onTechnicianLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTechnicianLoginCompleted);
        }
        base.InvokeAsync(this.onBeginTechnicianLoginDelegate, new object[] {
                    username,
                    passWD}, this.onEndTechnicianLoginDelegate, this.onTechnicianLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginHelpDeskWorkerList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginHelpDeskWorkerList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TechSupportService.WorkerData[] ITechSupportService1.EndHelpDeskWorkerList(System.IAsyncResult result)
    {
        return base.Channel.EndHelpDeskWorkerList(result);
    }
    
    private System.IAsyncResult OnBeginHelpDeskWorkerList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((ITechSupportService1)(this)).BeginHelpDeskWorkerList(callback, asyncState);
    }
    
    private object[] OnEndHelpDeskWorkerList(System.IAsyncResult result)
    {
        TechSupportService.WorkerData[] retVal = ((ITechSupportService1)(this)).EndHelpDeskWorkerList(result);
        return new object[] {
                retVal};
    }
    
    private void OnHelpDeskWorkerListCompleted(object state)
    {
        if ((this.HelpDeskWorkerListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.HelpDeskWorkerListCompleted(this, new HelpDeskWorkerListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void HelpDeskWorkerListAsync()
    {
        this.HelpDeskWorkerListAsync(null);
    }
    
    public void HelpDeskWorkerListAsync(object userState)
    {
        if ((this.onBeginHelpDeskWorkerListDelegate == null))
        {
            this.onBeginHelpDeskWorkerListDelegate = new BeginOperationDelegate(this.OnBeginHelpDeskWorkerList);
        }
        if ((this.onEndHelpDeskWorkerListDelegate == null))
        {
            this.onEndHelpDeskWorkerListDelegate = new EndOperationDelegate(this.OnEndHelpDeskWorkerList);
        }
        if ((this.onHelpDeskWorkerListCompletedDelegate == null))
        {
            this.onHelpDeskWorkerListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelpDeskWorkerListCompleted);
        }
        base.InvokeAsync(this.onBeginHelpDeskWorkerListDelegate, null, this.onEndHelpDeskWorkerListDelegate, this.onHelpDeskWorkerListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginCustomerList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCustomerList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TechSupportService.DataContract.CustomerData[] ITechSupportService1.EndCustomerList(System.IAsyncResult result)
    {
        return base.Channel.EndCustomerList(result);
    }
    
    private System.IAsyncResult OnBeginCustomerList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((ITechSupportService1)(this)).BeginCustomerList(callback, asyncState);
    }
    
    private object[] OnEndCustomerList(System.IAsyncResult result)
    {
        TechSupportService.DataContract.CustomerData[] retVal = ((ITechSupportService1)(this)).EndCustomerList(result);
        return new object[] {
                retVal};
    }
    
    private void OnCustomerListCompleted(object state)
    {
        if ((this.CustomerListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CustomerListCompleted(this, new CustomerListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CustomerListAsync()
    {
        this.CustomerListAsync(null);
    }
    
    public void CustomerListAsync(object userState)
    {
        if ((this.onBeginCustomerListDelegate == null))
        {
            this.onBeginCustomerListDelegate = new BeginOperationDelegate(this.OnBeginCustomerList);
        }
        if ((this.onEndCustomerListDelegate == null))
        {
            this.onEndCustomerListDelegate = new EndOperationDelegate(this.OnEndCustomerList);
        }
        if ((this.onCustomerListCompletedDelegate == null))
        {
            this.onCustomerListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCustomerListCompleted);
        }
        base.InvokeAsync(this.onBeginCustomerListDelegate, null, this.onEndCustomerListDelegate, this.onCustomerListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginGetMyNewTechworks(string username, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetMyNewTechworks(username, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TechSupportService.DataContract.NewTechWork[] ITechSupportService1.EndGetMyNewTechworks(System.IAsyncResult result)
    {
        return base.Channel.EndGetMyNewTechworks(result);
    }
    
    private System.IAsyncResult OnBeginGetMyNewTechworks(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        return ((ITechSupportService1)(this)).BeginGetMyNewTechworks(username, callback, asyncState);
    }
    
    private object[] OnEndGetMyNewTechworks(System.IAsyncResult result)
    {
        TechSupportService.DataContract.NewTechWork[] retVal = ((ITechSupportService1)(this)).EndGetMyNewTechworks(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetMyNewTechworksCompleted(object state)
    {
        if ((this.GetMyNewTechworksCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetMyNewTechworksCompleted(this, new GetMyNewTechworksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetMyNewTechworksAsync(string username)
    {
        this.GetMyNewTechworksAsync(username, null);
    }
    
    public void GetMyNewTechworksAsync(string username, object userState)
    {
        if ((this.onBeginGetMyNewTechworksDelegate == null))
        {
            this.onBeginGetMyNewTechworksDelegate = new BeginOperationDelegate(this.OnBeginGetMyNewTechworks);
        }
        if ((this.onEndGetMyNewTechworksDelegate == null))
        {
            this.onEndGetMyNewTechworksDelegate = new EndOperationDelegate(this.OnEndGetMyNewTechworks);
        }
        if ((this.onGetMyNewTechworksCompletedDelegate == null))
        {
            this.onGetMyNewTechworksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyNewTechworksCompleted);
        }
        base.InvokeAsync(this.onBeginGetMyNewTechworksDelegate, new object[] {
                    username}, this.onEndGetMyNewTechworksDelegate, this.onGetMyNewTechworksCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginUploadSolvedQuestion(TechSupportService.SolvedQuestion question, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUploadSolvedQuestion(question, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void ITechSupportService1.EndUploadSolvedQuestion(System.IAsyncResult result)
    {
        base.Channel.EndUploadSolvedQuestion(result);
    }
    
    private System.IAsyncResult OnBeginUploadSolvedQuestion(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        TechSupportService.SolvedQuestion question = ((TechSupportService.SolvedQuestion)(inValues[0]));
        return ((ITechSupportService1)(this)).BeginUploadSolvedQuestion(question, callback, asyncState);
    }
    
    private object[] OnEndUploadSolvedQuestion(System.IAsyncResult result)
    {
        ((ITechSupportService1)(this)).EndUploadSolvedQuestion(result);
        return null;
    }
    
    private void OnUploadSolvedQuestionCompleted(object state)
    {
        if ((this.UploadSolvedQuestionCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UploadSolvedQuestionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UploadSolvedQuestionAsync(TechSupportService.SolvedQuestion question)
    {
        this.UploadSolvedQuestionAsync(question, null);
    }
    
    public void UploadSolvedQuestionAsync(TechSupportService.SolvedQuestion question, object userState)
    {
        if ((this.onBeginUploadSolvedQuestionDelegate == null))
        {
            this.onBeginUploadSolvedQuestionDelegate = new BeginOperationDelegate(this.OnBeginUploadSolvedQuestion);
        }
        if ((this.onEndUploadSolvedQuestionDelegate == null))
        {
            this.onEndUploadSolvedQuestionDelegate = new EndOperationDelegate(this.OnEndUploadSolvedQuestion);
        }
        if ((this.onUploadSolvedQuestionCompletedDelegate == null))
        {
            this.onUploadSolvedQuestionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadSolvedQuestionCompleted);
        }
        base.InvokeAsync(this.onBeginUploadSolvedQuestionDelegate, new object[] {
                    question}, this.onEndUploadSolvedQuestionDelegate, this.onUploadSolvedQuestionCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginUserLogin(string username, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUserLogin(username, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool ITechSupportService1.EndUserLogin(System.IAsyncResult result)
    {
        return base.Channel.EndUserLogin(result);
    }
    
    private System.IAsyncResult OnBeginUserLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((ITechSupportService1)(this)).BeginUserLogin(username, password, callback, asyncState);
    }
    
    private object[] OnEndUserLogin(System.IAsyncResult result)
    {
        bool retVal = ((ITechSupportService1)(this)).EndUserLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnUserLoginCompleted(object state)
    {
        if ((this.UserLoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UserLoginCompleted(this, new UserLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UserLoginAsync(string username, string password)
    {
        this.UserLoginAsync(username, password, null);
    }
    
    public void UserLoginAsync(string username, string password, object userState)
    {
        if ((this.onBeginUserLoginDelegate == null))
        {
            this.onBeginUserLoginDelegate = new BeginOperationDelegate(this.OnBeginUserLogin);
        }
        if ((this.onEndUserLoginDelegate == null))
        {
            this.onEndUserLoginDelegate = new EndOperationDelegate(this.OnEndUserLogin);
        }
        if ((this.onUserLoginCompletedDelegate == null))
        {
            this.onUserLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUserLoginCompleted);
        }
        base.InvokeAsync(this.onBeginUserLoginDelegate, new object[] {
                    username,
                    password}, this.onEndUserLoginDelegate, this.onUserLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginGetProfilePicture(string username, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetProfilePicture(username, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string ITechSupportService1.EndGetProfilePicture(System.IAsyncResult result)
    {
        return base.Channel.EndGetProfilePicture(result);
    }
    
    private System.IAsyncResult OnBeginGetProfilePicture(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        return ((ITechSupportService1)(this)).BeginGetProfilePicture(username, callback, asyncState);
    }
    
    private object[] OnEndGetProfilePicture(System.IAsyncResult result)
    {
        string retVal = ((ITechSupportService1)(this)).EndGetProfilePicture(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetProfilePictureCompleted(object state)
    {
        if ((this.GetProfilePictureCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetProfilePictureCompleted(this, new GetProfilePictureCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetProfilePictureAsync(string username)
    {
        this.GetProfilePictureAsync(username, null);
    }
    
    public void GetProfilePictureAsync(string username, object userState)
    {
        if ((this.onBeginGetProfilePictureDelegate == null))
        {
            this.onBeginGetProfilePictureDelegate = new BeginOperationDelegate(this.OnBeginGetProfilePicture);
        }
        if ((this.onEndGetProfilePictureDelegate == null))
        {
            this.onEndGetProfilePictureDelegate = new EndOperationDelegate(this.OnEndGetProfilePicture);
        }
        if ((this.onGetProfilePictureCompletedDelegate == null))
        {
            this.onGetProfilePictureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProfilePictureCompleted);
        }
        base.InvokeAsync(this.onBeginGetProfilePictureDelegate, new object[] {
                    username}, this.onEndGetProfilePictureDelegate, this.onGetProfilePictureCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginGetUserProfilePicture(string username, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUserProfilePicture(username, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string ITechSupportService1.EndGetUserProfilePicture(System.IAsyncResult result)
    {
        return base.Channel.EndGetUserProfilePicture(result);
    }
    
    private System.IAsyncResult OnBeginGetUserProfilePicture(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        return ((ITechSupportService1)(this)).BeginGetUserProfilePicture(username, callback, asyncState);
    }
    
    private object[] OnEndGetUserProfilePicture(System.IAsyncResult result)
    {
        string retVal = ((ITechSupportService1)(this)).EndGetUserProfilePicture(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetUserProfilePictureCompleted(object state)
    {
        if ((this.GetUserProfilePictureCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetUserProfilePictureCompleted(this, new GetUserProfilePictureCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetUserProfilePictureAsync(string username)
    {
        this.GetUserProfilePictureAsync(username, null);
    }
    
    public void GetUserProfilePictureAsync(string username, object userState)
    {
        if ((this.onBeginGetUserProfilePictureDelegate == null))
        {
            this.onBeginGetUserProfilePictureDelegate = new BeginOperationDelegate(this.OnBeginGetUserProfilePicture);
        }
        if ((this.onEndGetUserProfilePictureDelegate == null))
        {
            this.onEndGetUserProfilePictureDelegate = new EndOperationDelegate(this.OnEndGetUserProfilePicture);
        }
        if ((this.onGetUserProfilePictureCompletedDelegate == null))
        {
            this.onGetUserProfilePictureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserProfilePictureCompleted);
        }
        base.InvokeAsync(this.onBeginGetUserProfilePictureDelegate, new object[] {
                    username}, this.onEndGetUserProfilePictureDelegate, this.onGetUserProfilePictureCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginRegisterNewUser(string fullName, string email, string userName, string password, string profilePicture, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRegisterNewUser(fullName, email, userName, password, profilePicture, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void ITechSupportService1.EndRegisterNewUser(System.IAsyncResult result)
    {
        base.Channel.EndRegisterNewUser(result);
    }
    
    private System.IAsyncResult OnBeginRegisterNewUser(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string fullName = ((string)(inValues[0]));
        string email = ((string)(inValues[1]));
        string userName = ((string)(inValues[2]));
        string password = ((string)(inValues[3]));
        string profilePicture = ((string)(inValues[4]));
        return ((ITechSupportService1)(this)).BeginRegisterNewUser(fullName, email, userName, password, profilePicture, callback, asyncState);
    }
    
    private object[] OnEndRegisterNewUser(System.IAsyncResult result)
    {
        ((ITechSupportService1)(this)).EndRegisterNewUser(result);
        return null;
    }
    
    private void OnRegisterNewUserCompleted(object state)
    {
        if ((this.RegisterNewUserCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.RegisterNewUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void RegisterNewUserAsync(string fullName, string email, string userName, string password, string profilePicture)
    {
        this.RegisterNewUserAsync(fullName, email, userName, password, profilePicture, null);
    }
    
    public void RegisterNewUserAsync(string fullName, string email, string userName, string password, string profilePicture, object userState)
    {
        if ((this.onBeginRegisterNewUserDelegate == null))
        {
            this.onBeginRegisterNewUserDelegate = new BeginOperationDelegate(this.OnBeginRegisterNewUser);
        }
        if ((this.onEndRegisterNewUserDelegate == null))
        {
            this.onEndRegisterNewUserDelegate = new EndOperationDelegate(this.OnEndRegisterNewUser);
        }
        if ((this.onRegisterNewUserCompletedDelegate == null))
        {
            this.onRegisterNewUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterNewUserCompleted);
        }
        base.InvokeAsync(this.onBeginRegisterNewUserDelegate, new object[] {
                    fullName,
                    email,
                    userName,
                    password,
                    profilePicture}, this.onEndRegisterNewUserDelegate, this.onRegisterNewUserCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginSendMessageToSupport(string username, string sender, string message, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSendMessageToSupport(username, sender, message, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void ITechSupportService1.EndSendMessageToSupport(System.IAsyncResult result)
    {
        base.Channel.EndSendMessageToSupport(result);
    }
    
    private System.IAsyncResult OnBeginSendMessageToSupport(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        string sender = ((string)(inValues[1]));
        string message = ((string)(inValues[2]));
        return ((ITechSupportService1)(this)).BeginSendMessageToSupport(username, sender, message, callback, asyncState);
    }
    
    private object[] OnEndSendMessageToSupport(System.IAsyncResult result)
    {
        ((ITechSupportService1)(this)).EndSendMessageToSupport(result);
        return null;
    }
    
    private void OnSendMessageToSupportCompleted(object state)
    {
        if ((this.SendMessageToSupportCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SendMessageToSupportCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SendMessageToSupportAsync(string username, string sender, string message)
    {
        this.SendMessageToSupportAsync(username, sender, message, null);
    }
    
    public void SendMessageToSupportAsync(string username, string sender, string message, object userState)
    {
        if ((this.onBeginSendMessageToSupportDelegate == null))
        {
            this.onBeginSendMessageToSupportDelegate = new BeginOperationDelegate(this.OnBeginSendMessageToSupport);
        }
        if ((this.onEndSendMessageToSupportDelegate == null))
        {
            this.onEndSendMessageToSupportDelegate = new EndOperationDelegate(this.OnEndSendMessageToSupport);
        }
        if ((this.onSendMessageToSupportCompletedDelegate == null))
        {
            this.onSendMessageToSupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMessageToSupportCompleted);
        }
        base.InvokeAsync(this.onBeginSendMessageToSupportDelegate, new object[] {
                    username,
                    sender,
                    message}, this.onEndSendMessageToSupportDelegate, this.onSendMessageToSupportCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult ITechSupportService1.BeginGetMyMessages(string username, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetMyMessages(username, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    TechSupportService.DataContract.Message[] ITechSupportService1.EndGetMyMessages(System.IAsyncResult result)
    {
        return base.Channel.EndGetMyMessages(result);
    }
    
    private System.IAsyncResult OnBeginGetMyMessages(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string username = ((string)(inValues[0]));
        return ((ITechSupportService1)(this)).BeginGetMyMessages(username, callback, asyncState);
    }
    
    private object[] OnEndGetMyMessages(System.IAsyncResult result)
    {
        TechSupportService.DataContract.Message[] retVal = ((ITechSupportService1)(this)).EndGetMyMessages(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetMyMessagesCompleted(object state)
    {
        if ((this.GetMyMessagesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetMyMessagesCompleted(this, new GetMyMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetMyMessagesAsync(string username)
    {
        this.GetMyMessagesAsync(username, null);
    }
    
    public void GetMyMessagesAsync(string username, object userState)
    {
        if ((this.onBeginGetMyMessagesDelegate == null))
        {
            this.onBeginGetMyMessagesDelegate = new BeginOperationDelegate(this.OnBeginGetMyMessages);
        }
        if ((this.onEndGetMyMessagesDelegate == null))
        {
            this.onEndGetMyMessagesDelegate = new EndOperationDelegate(this.OnEndGetMyMessages);
        }
        if ((this.onGetMyMessagesCompletedDelegate == null))
        {
            this.onGetMyMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMyMessagesCompleted);
        }
        base.InvokeAsync(this.onBeginGetMyMessagesDelegate, new object[] {
                    username}, this.onEndGetMyMessagesDelegate, this.onGetMyMessagesCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override ITechSupportService1 CreateChannel()
    {
        return new TechSupportService1ClientChannel(this);
    }
    
    private class TechSupportService1ClientChannel : ChannelBase<ITechSupportService1>, ITechSupportService1
    {
        
        public TechSupportService1ClientChannel(System.ServiceModel.ClientBase<ITechSupportService1> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginTechnicianLogin(string username, string passWD, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = username;
            _args[1] = passWD;
            System.IAsyncResult _result = base.BeginInvoke("TechnicianLogin", _args, callback, asyncState);
            return _result;
        }
        
        public TechSupportService.LoginResult EndTechnicianLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TechSupportService.LoginResult _result = ((TechSupportService.LoginResult)(base.EndInvoke("TechnicianLogin", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginHelpDeskWorkerList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("HelpDeskWorkerList", _args, callback, asyncState);
            return _result;
        }
        
        public TechSupportService.WorkerData[] EndHelpDeskWorkerList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TechSupportService.WorkerData[] _result = ((TechSupportService.WorkerData[])(base.EndInvoke("HelpDeskWorkerList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginCustomerList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("CustomerList", _args, callback, asyncState);
            return _result;
        }
        
        public TechSupportService.DataContract.CustomerData[] EndCustomerList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TechSupportService.DataContract.CustomerData[] _result = ((TechSupportService.DataContract.CustomerData[])(base.EndInvoke("CustomerList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetMyNewTechworks(string username, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = username;
            System.IAsyncResult _result = base.BeginInvoke("GetMyNewTechworks", _args, callback, asyncState);
            return _result;
        }
        
        public TechSupportService.DataContract.NewTechWork[] EndGetMyNewTechworks(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TechSupportService.DataContract.NewTechWork[] _result = ((TechSupportService.DataContract.NewTechWork[])(base.EndInvoke("GetMyNewTechworks", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUploadSolvedQuestion(TechSupportService.SolvedQuestion question, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = question;
            System.IAsyncResult _result = base.BeginInvoke("UploadSolvedQuestion", _args, callback, asyncState);
            return _result;
        }
        
        public void EndUploadSolvedQuestion(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("UploadSolvedQuestion", _args, result);
        }
        
        public System.IAsyncResult BeginUserLogin(string username, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = username;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("UserLogin", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndUserLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("UserLogin", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetProfilePicture(string username, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = username;
            System.IAsyncResult _result = base.BeginInvoke("GetProfilePicture", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetProfilePicture(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetProfilePicture", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetUserProfilePicture(string username, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = username;
            System.IAsyncResult _result = base.BeginInvoke("GetUserProfilePicture", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetUserProfilePicture(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetUserProfilePicture", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginRegisterNewUser(string fullName, string email, string userName, string password, string profilePicture, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[5];
            _args[0] = fullName;
            _args[1] = email;
            _args[2] = userName;
            _args[3] = password;
            _args[4] = profilePicture;
            System.IAsyncResult _result = base.BeginInvoke("RegisterNewUser", _args, callback, asyncState);
            return _result;
        }
        
        public void EndRegisterNewUser(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("RegisterNewUser", _args, result);
        }
        
        public System.IAsyncResult BeginSendMessageToSupport(string username, string sender, string message, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = username;
            _args[1] = sender;
            _args[2] = message;
            System.IAsyncResult _result = base.BeginInvoke("SendMessageToSupport", _args, callback, asyncState);
            return _result;
        }
        
        public void EndSendMessageToSupport(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("SendMessageToSupport", _args, result);
        }
        
        public System.IAsyncResult BeginGetMyMessages(string username, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = username;
            System.IAsyncResult _result = base.BeginInvoke("GetMyMessages", _args, callback, asyncState);
            return _result;
        }
        
        public TechSupportService.DataContract.Message[] EndGetMyMessages(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            TechSupportService.DataContract.Message[] _result = ((TechSupportService.DataContract.Message[])(base.EndInvoke("GetMyMessages", _args, result)));
            return _result;
        }
    }
}
