//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchProject.TechSupportSecure {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valid {
            get {
                return this.ValidField;
            }
            set {
                if ((this.ValidField.Equals(value) != true)) {
                    this.ValidField = value;
                    this.RaisePropertyChanged("Valid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HelpDesk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technician = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boss = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchProject.TechSupportSecure.TechnicianData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SchProject.TechSupportSecure.WorkerDataRegistrationData))]
    public partial class WorkerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicianData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class TechnicianData : SchProject.TechSupportSecure.WorkerData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TechnicianIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.TechnicianStatus TechnicianStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TechnicianID {
            get {
                return this.TechnicianIDField;
            }
            set {
                if ((this.TechnicianIDField.Equals(value) != true)) {
                    this.TechnicianIDField = value;
                    this.RaisePropertyChanged("TechnicianID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.TechnicianStatus TechnicianStatus {
            get {
                return this.TechnicianStatusField;
            }
            set {
                if ((this.TechnicianStatusField.Equals(value) != true)) {
                    this.TechnicianStatusField = value;
                    this.RaisePropertyChanged("TechnicianStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerDataRegistrationData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class WorkerDataRegistrationData : SchProject.TechSupportSecure.WorkerData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.Bank BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.Bank Bank {
            get {
                return this.BankField;
            }
            set {
                if ((this.BankField.Equals(value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWD {
            get {
                return this.PassWDField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWDField, value) != true)) {
                    this.PassWDField = value;
                    this.RaisePropertyChanged("PassWD");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Away = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public enum Bank : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MagyarNemzetiBank = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erste = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrszágosTakarékPénztár = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTP = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicianStatus", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public enum TechnicianStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromCustomer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AtCustomer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Break = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegTime {
            get {
                return this.RegTimeField;
            }
            set {
                if ((this.RegTimeField.Equals(value) != true)) {
                    this.RegTimeField = value;
                    this.RaisePropertyChanged("RegTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolvedQuestion", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class SolvedQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] KeyWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeAnsweredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeAskedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] KeyWords {
            get {
                return this.KeyWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordsField, value) != true)) {
                    this.KeyWordsField = value;
                    this.RaisePropertyChanged("KeyWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAnswered {
            get {
                return this.TimeAnsweredField;
            }
            set {
                if ((this.TimeAnsweredField.Equals(value) != true)) {
                    this.TimeAnsweredField = value;
                    this.RaisePropertyChanged("TimeAnswered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAsked {
            get {
                return this.TimeAskedField;
            }
            set {
                if ((this.TimeAskedField.Equals(value) != true)) {
                    this.TimeAskedField = value;
                    this.RaisePropertyChanged("TimeAsked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerID {
            get {
                return this.WorkerIDField;
            }
            set {
                if ((this.WorkerIDField.Equals(value) != true)) {
                    this.WorkerIDField = value;
                    this.RaisePropertyChanged("WorkerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerName {
            get {
                return this.WorkerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerNameField, value) != true)) {
                    this.WorkerNameField = value;
                    this.RaisePropertyChanged("WorkerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechWork", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class TechWork : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.CustomerData CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SchProject.TechSupportSecure.TechnicianData TechnicianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.CustomerData Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((this.FinishField.Equals(value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SchProject.TechSupportSecure.TechnicianData Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicianField, value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TechSupportSecure.ITechSupportServiceSecure1")]
    public interface ITechSupportServiceSecure1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/Login", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LoginResponse")]
        SchProject.TechSupportSecure.LoginResult Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/Login", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LoginResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.LoginResult> LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterNewStaffMember")]
        void RegisterNewStaffMember(SchProject.TechSupportSecure.WorkerDataRegistrationData regData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterNewStaffMember")]
        System.Threading.Tasks.Task RegisterNewStaffMemberAsync(SchProject.TechSupportSecure.WorkerDataRegistrationData regData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerListResponse")]
        SchProject.TechSupportSecure.CustomerData[] LastCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerListResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData[]> LastCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/StaffList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/StaffListResponse")]
        SchProject.TechSupportSecure.WorkerData[] StaffList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/StaffList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/StaffListResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.WorkerData[]> StaffListAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerStatus")]
        void ChangeWorkerStatus(string username, SchProject.TechSupportSecure.Status status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerStatus")]
        System.Threading.Tasks.Task ChangeWorkerStatusAsync(string username, SchProject.TechSupportSecure.Status status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyStatus")]
        void ChangeMyStatus(SchProject.TechSupportSecure.Status newStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyStatus")]
        System.Threading.Tasks.Task ChangeMyStatusAsync(SchProject.TechSupportSecure.Status newStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/SendBugreport")]
        void SendBugreport(string message, string[] file);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/SendBugreport")]
        System.Threading.Tasks.Task SendBugreportAsync(string message, string[] file);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerPassWD")]
        void ChangeWorkerPassWD(string username, string newPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerPassWD")]
        System.Threading.Tasks.Task ChangeWorkerPassWDAsync(string username, string newPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangePassWD")]
        void ChangePassWD(string passnewPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangePassWD")]
        System.Threading.Tasks.Task ChangePassWDAsync(string passnewPassWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorker", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerResponse")]
        SchProject.TechSupportSecure.WorkerData GetWorker(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorker", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.WorkerData> GetWorkerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/TechnicianList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/TechnicianListResponse")]
        SchProject.TechSupportSecure.TechnicianData[] TechnicianList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/TechnicianList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/TechnicianListResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechnicianData[]> TechnicianListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnicianResponse")]
        SchProject.TechSupportSecure.TechnicianData[] GetAvailableTechnician();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnicianResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechnicianData[]> GetAvailableTechnicianAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/AddNewSolvedQuestion")]
        void AddNewSolvedQuestion(SchProject.TechSupportSecure.SolvedQuestion solved);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/AddNewSolvedQuestion")]
        System.Threading.Tasks.Task AddNewSolvedQuestionAsync(SchProject.TechSupportSecure.SolvedQuestion solved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionListResponse")]
        SchProject.TechSupportSecure.SolvedQuestion[] SolvedQuestionList(uint Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionListResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.SolvedQuestion[]> SolvedQuestionListAsync(uint Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorksResponse")]
        SchProject.TechSupportSecure.TechWork[] GetTechWorks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorksResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechWork[]> GetTechWorksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorksResponse")]
        SchProject.TechSupportSecure.TechWork[] NewTechWorks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorksResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechWork[]> NewTechWorksAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeTechnicianStatus")]
        void ChangeTechnicianStatus(SchProject.TechSupportSecure.TechnicianStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeTechnicianStatus")]
        System.Threading.Tasks.Task ChangeTechnicianStatusAsync(SchProject.TechSupportSecure.TechnicianStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterTechWork")]
        void RegisterTechWork(SchProject.TechSupportSecure.TechWork work);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterTechWork")]
        System.Threading.Tasks.Task RegisterTechWorkAsync(SchProject.TechSupportSecure.TechWork work);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerResponse")]
        SchProject.TechSupportSecure.CustomerData LastCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData> LastCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetCustomerResponse")]
        SchProject.TechSupportSecure.CustomerData GetCustomer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetCustomerResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData> GetCustomerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetLastSevedDaysSolves", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetLastSevedDaysSolvesResponse")]
        SchProject.TechSupportSecure.GetLastSevedDaysSolvesResponse GetLastSevedDaysSolves(SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetLastSevedDaysSolves", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetLastSevedDaysSolvesResponse")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.GetLastSevedDaysSolvesResponse> GetLastSevedDaysSolvesAsync(SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyPassWD")]
        void ChangeMyPassWD(string newPass);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyPassWD")]
        System.Threading.Tasks.Task ChangeMyPassWDAsync(string newPass);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyPicture")]
        void ChangeMyPicture(string picture);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeMyPicture")]
        System.Threading.Tasks.Task ChangeMyPictureAsync(string picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/CheckMyPassWD", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/CheckMyPassWDResponse")]
        bool CheckMyPassWD(string passWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/CheckMyPassWD", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/CheckMyPassWDResponse")]
        System.Threading.Tasks.Task<bool> CheckMyPassWDAsync(string passWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetLastMonthRegistratedUsers", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetLastMonthRegistratedUsersRespons" +
            "e")]
        SchProject.TechSupportSecure.GetLastMonthRegistratedUsersResponse GetLastMonthRegistratedUsers(SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetLastMonthRegistratedUsers", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetLastMonthRegistratedUsersRespons" +
            "e")]
        System.Threading.Tasks.Task<SchProject.TechSupportSecure.GetLastMonthRegistratedUsersResponse> GetLastMonthRegistratedUsersAsync(SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SendMessageToTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SendMessageToTechnicianResponse")]
        void SendMessageToTechnician(string username, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SendMessageToTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SendMessageToTechnicianResponse")]
        System.Threading.Tasks.Task SendMessageToTechnicianAsync(string username, string message);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastSevedDaysSolves", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastSevedDaysSolvesRequest {
        
        public GetLastSevedDaysSolvesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastSevedDaysSolvesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastSevedDaysSolvesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetLastSevedDaysSolvesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime[] dates;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Collections.Generic.KeyValuePair<string, int>[] byName;
        
        public GetLastSevedDaysSolvesResponse() {
        }
        
        public GetLastSevedDaysSolvesResponse(int[] GetLastSevedDaysSolvesResult, System.DateTime[] dates, System.Collections.Generic.KeyValuePair<string, int>[] byName) {
            this.GetLastSevedDaysSolvesResult = GetLastSevedDaysSolvesResult;
            this.dates = dates;
            this.byName = byName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastMonthRegistratedUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastMonthRegistratedUsersRequest {
        
        public GetLastMonthRegistratedUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastMonthRegistratedUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastMonthRegistratedUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] GetLastMonthRegistratedUsersResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime[] Dates;
        
        public GetLastMonthRegistratedUsersResponse() {
        }
        
        public GetLastMonthRegistratedUsersResponse(int[] GetLastMonthRegistratedUsersResult, System.DateTime[] Dates) {
            this.GetLastMonthRegistratedUsersResult = GetLastMonthRegistratedUsersResult;
            this.Dates = Dates;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITechSupportServiceSecure1Channel : SchProject.TechSupportSecure.ITechSupportServiceSecure1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TechSupportServiceSecure1Client : System.ServiceModel.ClientBase<SchProject.TechSupportSecure.ITechSupportServiceSecure1>, SchProject.TechSupportSecure.ITechSupportServiceSecure1 {
        
        public TechSupportServiceSecure1Client() {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechSupportServiceSecure1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SchProject.TechSupportSecure.LoginResult Login() {
            return base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.LoginResult> LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public void RegisterNewStaffMember(SchProject.TechSupportSecure.WorkerDataRegistrationData regData) {
            base.Channel.RegisterNewStaffMember(regData);
        }
        
        public System.Threading.Tasks.Task RegisterNewStaffMemberAsync(SchProject.TechSupportSecure.WorkerDataRegistrationData regData) {
            return base.Channel.RegisterNewStaffMemberAsync(regData);
        }
        
        public SchProject.TechSupportSecure.CustomerData[] LastCustomerList() {
            return base.Channel.LastCustomerList();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData[]> LastCustomerListAsync() {
            return base.Channel.LastCustomerListAsync();
        }
        
        public SchProject.TechSupportSecure.WorkerData[] StaffList() {
            return base.Channel.StaffList();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.WorkerData[]> StaffListAsync() {
            return base.Channel.StaffListAsync();
        }
        
        public void ChangeWorkerStatus(string username, SchProject.TechSupportSecure.Status status) {
            base.Channel.ChangeWorkerStatus(username, status);
        }
        
        public System.Threading.Tasks.Task ChangeWorkerStatusAsync(string username, SchProject.TechSupportSecure.Status status) {
            return base.Channel.ChangeWorkerStatusAsync(username, status);
        }
        
        public void ChangeMyStatus(SchProject.TechSupportSecure.Status newStatus) {
            base.Channel.ChangeMyStatus(newStatus);
        }
        
        public System.Threading.Tasks.Task ChangeMyStatusAsync(SchProject.TechSupportSecure.Status newStatus) {
            return base.Channel.ChangeMyStatusAsync(newStatus);
        }
        
        public void SendBugreport(string message, string[] file) {
            base.Channel.SendBugreport(message, file);
        }
        
        public System.Threading.Tasks.Task SendBugreportAsync(string message, string[] file) {
            return base.Channel.SendBugreportAsync(message, file);
        }
        
        public void ChangeWorkerPassWD(string username, string newPassWD) {
            base.Channel.ChangeWorkerPassWD(username, newPassWD);
        }
        
        public System.Threading.Tasks.Task ChangeWorkerPassWDAsync(string username, string newPassWD) {
            return base.Channel.ChangeWorkerPassWDAsync(username, newPassWD);
        }
        
        public void ChangePassWD(string passnewPassWD) {
            base.Channel.ChangePassWD(passnewPassWD);
        }
        
        public System.Threading.Tasks.Task ChangePassWDAsync(string passnewPassWD) {
            return base.Channel.ChangePassWDAsync(passnewPassWD);
        }
        
        public SchProject.TechSupportSecure.WorkerData GetWorker(string username) {
            return base.Channel.GetWorker(username);
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.WorkerData> GetWorkerAsync(string username) {
            return base.Channel.GetWorkerAsync(username);
        }
        
        public SchProject.TechSupportSecure.TechnicianData[] TechnicianList() {
            return base.Channel.TechnicianList();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechnicianData[]> TechnicianListAsync() {
            return base.Channel.TechnicianListAsync();
        }
        
        public SchProject.TechSupportSecure.TechnicianData[] GetAvailableTechnician() {
            return base.Channel.GetAvailableTechnician();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechnicianData[]> GetAvailableTechnicianAsync() {
            return base.Channel.GetAvailableTechnicianAsync();
        }
        
        public void AddNewSolvedQuestion(SchProject.TechSupportSecure.SolvedQuestion solved) {
            base.Channel.AddNewSolvedQuestion(solved);
        }
        
        public System.Threading.Tasks.Task AddNewSolvedQuestionAsync(SchProject.TechSupportSecure.SolvedQuestion solved) {
            return base.Channel.AddNewSolvedQuestionAsync(solved);
        }
        
        public SchProject.TechSupportSecure.SolvedQuestion[] SolvedQuestionList(uint Page) {
            return base.Channel.SolvedQuestionList(Page);
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.SolvedQuestion[]> SolvedQuestionListAsync(uint Page) {
            return base.Channel.SolvedQuestionListAsync(Page);
        }
        
        public SchProject.TechSupportSecure.TechWork[] GetTechWorks() {
            return base.Channel.GetTechWorks();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechWork[]> GetTechWorksAsync() {
            return base.Channel.GetTechWorksAsync();
        }
        
        public SchProject.TechSupportSecure.TechWork[] NewTechWorks() {
            return base.Channel.NewTechWorks();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.TechWork[]> NewTechWorksAsync() {
            return base.Channel.NewTechWorksAsync();
        }
        
        public void ChangeTechnicianStatus(SchProject.TechSupportSecure.TechnicianStatus status) {
            base.Channel.ChangeTechnicianStatus(status);
        }
        
        public System.Threading.Tasks.Task ChangeTechnicianStatusAsync(SchProject.TechSupportSecure.TechnicianStatus status) {
            return base.Channel.ChangeTechnicianStatusAsync(status);
        }
        
        public void RegisterTechWork(SchProject.TechSupportSecure.TechWork work) {
            base.Channel.RegisterTechWork(work);
        }
        
        public System.Threading.Tasks.Task RegisterTechWorkAsync(SchProject.TechSupportSecure.TechWork work) {
            return base.Channel.RegisterTechWorkAsync(work);
        }
        
        public SchProject.TechSupportSecure.CustomerData LastCustomer() {
            return base.Channel.LastCustomer();
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData> LastCustomerAsync() {
            return base.Channel.LastCustomerAsync();
        }
        
        public SchProject.TechSupportSecure.CustomerData GetCustomer(string username) {
            return base.Channel.GetCustomer(username);
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.CustomerData> GetCustomerAsync(string username) {
            return base.Channel.GetCustomerAsync(username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchProject.TechSupportSecure.GetLastSevedDaysSolvesResponse SchProject.TechSupportSecure.ITechSupportServiceSecure1.GetLastSevedDaysSolves(SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest request) {
            return base.Channel.GetLastSevedDaysSolves(request);
        }
        
        public int[] GetLastSevedDaysSolves(out System.DateTime[] dates, out System.Collections.Generic.KeyValuePair<string, int>[] byName) {
            SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest inValue = new SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest();
            SchProject.TechSupportSecure.GetLastSevedDaysSolvesResponse retVal = ((SchProject.TechSupportSecure.ITechSupportServiceSecure1)(this)).GetLastSevedDaysSolves(inValue);
            dates = retVal.dates;
            byName = retVal.byName;
            return retVal.GetLastSevedDaysSolvesResult;
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.GetLastSevedDaysSolvesResponse> GetLastSevedDaysSolvesAsync(SchProject.TechSupportSecure.GetLastSevedDaysSolvesRequest request) {
            return base.Channel.GetLastSevedDaysSolvesAsync(request);
        }
        
        public void ChangeMyPassWD(string newPass) {
            base.Channel.ChangeMyPassWD(newPass);
        }
        
        public System.Threading.Tasks.Task ChangeMyPassWDAsync(string newPass) {
            return base.Channel.ChangeMyPassWDAsync(newPass);
        }
        
        public void ChangeMyPicture(string picture) {
            base.Channel.ChangeMyPicture(picture);
        }
        
        public System.Threading.Tasks.Task ChangeMyPictureAsync(string picture) {
            return base.Channel.ChangeMyPictureAsync(picture);
        }
        
        public bool CheckMyPassWD(string passWD) {
            return base.Channel.CheckMyPassWD(passWD);
        }
        
        public System.Threading.Tasks.Task<bool> CheckMyPassWDAsync(string passWD) {
            return base.Channel.CheckMyPassWDAsync(passWD);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SchProject.TechSupportSecure.GetLastMonthRegistratedUsersResponse SchProject.TechSupportSecure.ITechSupportServiceSecure1.GetLastMonthRegistratedUsers(SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest request) {
            return base.Channel.GetLastMonthRegistratedUsers(request);
        }
        
        public int[] GetLastMonthRegistratedUsers(out System.DateTime[] Dates) {
            SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest inValue = new SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest();
            SchProject.TechSupportSecure.GetLastMonthRegistratedUsersResponse retVal = ((SchProject.TechSupportSecure.ITechSupportServiceSecure1)(this)).GetLastMonthRegistratedUsers(inValue);
            Dates = retVal.Dates;
            return retVal.GetLastMonthRegistratedUsersResult;
        }
        
        public System.Threading.Tasks.Task<SchProject.TechSupportSecure.GetLastMonthRegistratedUsersResponse> GetLastMonthRegistratedUsersAsync(SchProject.TechSupportSecure.GetLastMonthRegistratedUsersRequest request) {
            return base.Channel.GetLastMonthRegistratedUsersAsync(request);
        }
        
        public void SendMessageToTechnician(string username, string message) {
            base.Channel.SendMessageToTechnician(username, message);
        }
        
        public System.Threading.Tasks.Task SendMessageToTechnicianAsync(string username, string message) {
            return base.Channel.SendMessageToTechnicianAsync(username, message);
        }
    }
}
