//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAndRepositoryTests.SecureService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class LoginResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Security.SecureString UUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Security.SecureString UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valid {
            get {
                return this.ValidField;
            }
            set {
                if ((this.ValidField.Equals(value) != true)) {
                    this.ValidField = value;
                    this.RaisePropertyChanged("Valid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HelpDesk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Technician = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boss = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DatabaseAndRepositoryTests.SecureService.TechnicianData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DatabaseAndRepositoryTests.SecureService.WorkerDataRegistrationData))]
    public partial class WorkerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicianData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class TechnicianData : DatabaseAndRepositoryTests.SecureService.WorkerData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TechnicianIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.TechnicianStatus TechnicianStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TechnicianID {
            get {
                return this.TechnicianIDField;
            }
            set {
                if ((this.TechnicianIDField.Equals(value) != true)) {
                    this.TechnicianIDField = value;
                    this.RaisePropertyChanged("TechnicianID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.TechnicianStatus TechnicianStatus {
            get {
                return this.TechnicianStatusField;
            }
            set {
                if ((this.TechnicianStatusField.Equals(value) != true)) {
                    this.TechnicianStatusField = value;
                    this.RaisePropertyChanged("TechnicianStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkerDataRegistrationData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class WorkerDataRegistrationData : DatabaseAndRepositoryTests.SecureService.WorkerData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.Bank BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TechnicianField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.Bank Bank {
            get {
                return this.BankField;
            }
            set {
                if ((this.BankField.Equals(value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWD {
            get {
                return this.PassWDField;
            }
            set {
                if ((object.ReferenceEquals(this.PassWDField, value) != true)) {
                    this.PassWDField = value;
                    this.RaisePropertyChanged("PassWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((this.TechnicianField.Equals(value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Away = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Working = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    public enum Bank : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MagyarNemzetiBank = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erste = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrszágosTakarékPénztár = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTP = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicianStatus", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    public enum TechnicianStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromCustomer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AtCustomer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Break = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegTime {
            get {
                return this.RegTimeField;
            }
            set {
                if ((this.RegTimeField.Equals(value) != true)) {
                    this.RegTimeField = value;
                    this.RaisePropertyChanged("RegTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolvedQuestion", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService")]
    [System.SerializableAttribute()]
    public partial class SolvedQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] KeyWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeAnsweredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeAskedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TopicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] KeyWords {
            get {
                return this.KeyWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordsField, value) != true)) {
                    this.KeyWordsField = value;
                    this.RaisePropertyChanged("KeyWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAnswered {
            get {
                return this.TimeAnsweredField;
            }
            set {
                if ((this.TimeAnsweredField.Equals(value) != true)) {
                    this.TimeAnsweredField = value;
                    this.RaisePropertyChanged("TimeAnswered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeAsked {
            get {
                return this.TimeAskedField;
            }
            set {
                if ((this.TimeAskedField.Equals(value) != true)) {
                    this.TimeAskedField = value;
                    this.RaisePropertyChanged("TimeAsked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerName {
            get {
                return this.WorkerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerNameField, value) != true)) {
                    this.WorkerNameField = value;
                    this.RaisePropertyChanged("WorkerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechWork", Namespace="http://schemas.datacontract.org/2004/07/TechSupportService.DataContract")]
    [System.SerializableAttribute()]
    public partial class TechWork : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.CustomerData CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DatabaseAndRepositoryTests.SecureService.TechnicianData TechnicianField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.CustomerData Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((this.FinishField.Equals(value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DatabaseAndRepositoryTests.SecureService.TechnicianData Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicianField, value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecureService.ITechSupportServiceSecure1")]
    public interface ITechSupportServiceSecure1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerData", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerDataResponse")]
        DatabaseAndRepositoryTests.SecureService.LoginResult GetWorkerData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerData", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerDataResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.LoginResult> GetWorkerDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterNewStaffMember")]
        void RegisterNewStaffMember(DatabaseAndRepositoryTests.SecureService.WorkerDataRegistrationData regData);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterNewStaffMember")]
        System.Threading.Tasks.Task RegisterNewStaffMemberAsync(DatabaseAndRepositoryTests.SecureService.WorkerDataRegistrationData regData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerListResponse")]
        DatabaseAndRepositoryTests.SecureService.CustomerData[] LastCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerListResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData[]> LastCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/StaffList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/StaffListResponse")]
        DatabaseAndRepositoryTests.SecureService.WorkerData[] StaffList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/StaffList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/StaffListResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.WorkerData[]> StaffListAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerStatus")]
        void ChangeWorkerStatus(string username, DatabaseAndRepositoryTests.SecureService.Status status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerStatus")]
        System.Threading.Tasks.Task ChangeWorkerStatusAsync(string username, DatabaseAndRepositoryTests.SecureService.Status status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/SendBugreport")]
        void SendBugreport(string message, string[] file);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/SendBugreport")]
        System.Threading.Tasks.Task SendBugreportAsync(string message, string[] file);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerPassWD")]
        void ChangeWorkerPassWD(string username, string newPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeWorkerPassWD")]
        System.Threading.Tasks.Task ChangeWorkerPassWDAsync(string username, string newPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangePassWD")]
        void ChangePassWD(string passnewPassWD);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangePassWD")]
        System.Threading.Tasks.Task ChangePassWDAsync(string passnewPassWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorker", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerResponse")]
        DatabaseAndRepositoryTests.SecureService.WorkerData GetWorker(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetWorker", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetWorkerResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.WorkerData> GetWorkerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/TechnicianList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/TechnicianListResponse")]
        DatabaseAndRepositoryTests.SecureService.TechnicianData[] TechnicianList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/TechnicianList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/TechnicianListResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechnicianData[]> TechnicianListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnicianResponse")]
        DatabaseAndRepositoryTests.SecureService.TechnicianData[] GetAvailableTechnician();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnician", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetAvailableTechnicianResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechnicianData[]> GetAvailableTechnicianAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/AddNewSolvedQuestion")]
        void AddNewSolvedQuestion(DatabaseAndRepositoryTests.SecureService.SolvedQuestion solved);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/AddNewSolvedQuestion")]
        System.Threading.Tasks.Task AddNewSolvedQuestionAsync(DatabaseAndRepositoryTests.SecureService.SolvedQuestion solved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionListResponse")]
        DatabaseAndRepositoryTests.SecureService.SolvedQuestion[] SolvedQuestionList(uint Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionList", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/SolvedQuestionListResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.SolvedQuestion[]> SolvedQuestionListAsync(uint Page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorksResponse")]
        DatabaseAndRepositoryTests.SecureService.TechWork[] GetTechWorks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetTechWorksResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechWork[]> GetTechWorksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorksResponse")]
        DatabaseAndRepositoryTests.SecureService.TechWork[] NewTechWorks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorks", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/NewTechWorksResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechWork[]> NewTechWorksAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeTechnicianStatus")]
        void ChangeTechnicianStatus(DatabaseAndRepositoryTests.SecureService.TechnicianStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/ChangeTechnicianStatus")]
        System.Threading.Tasks.Task ChangeTechnicianStatusAsync(DatabaseAndRepositoryTests.SecureService.TechnicianStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterTechWork")]
        void RegisterTechWork(DatabaseAndRepositoryTests.SecureService.TechWork work);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITechSupportServiceSecure1/RegisterTechWork")]
        System.Threading.Tasks.Task RegisterTechWorkAsync(DatabaseAndRepositoryTests.SecureService.TechWork work);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerResponse")]
        DatabaseAndRepositoryTests.SecureService.CustomerData LastCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/LastCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/LastCustomerResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData> LastCustomerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetCustomerResponse")]
        DatabaseAndRepositoryTests.SecureService.CustomerData GetCustomer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITechSupportServiceSecure1/GetCustomer", ReplyAction="http://tempuri.org/ITechSupportServiceSecure1/GetCustomerResponse")]
        System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData> GetCustomerAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITechSupportServiceSecure1Channel : DatabaseAndRepositoryTests.SecureService.ITechSupportServiceSecure1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TechSupportServiceSecure1Client : System.ServiceModel.ClientBase<DatabaseAndRepositoryTests.SecureService.ITechSupportServiceSecure1>, DatabaseAndRepositoryTests.SecureService.ITechSupportServiceSecure1 {
        
        public TechSupportServiceSecure1Client() {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechSupportServiceSecure1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechSupportServiceSecure1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DatabaseAndRepositoryTests.SecureService.LoginResult GetWorkerData() {
            return base.Channel.GetWorkerData();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.LoginResult> GetWorkerDataAsync() {
            return base.Channel.GetWorkerDataAsync();
        }
        
        public void RegisterNewStaffMember(DatabaseAndRepositoryTests.SecureService.WorkerDataRegistrationData regData) {
            base.Channel.RegisterNewStaffMember(regData);
        }
        
        public System.Threading.Tasks.Task RegisterNewStaffMemberAsync(DatabaseAndRepositoryTests.SecureService.WorkerDataRegistrationData regData) {
            return base.Channel.RegisterNewStaffMemberAsync(regData);
        }
        
        public DatabaseAndRepositoryTests.SecureService.CustomerData[] LastCustomerList() {
            return base.Channel.LastCustomerList();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData[]> LastCustomerListAsync() {
            return base.Channel.LastCustomerListAsync();
        }
        
        public DatabaseAndRepositoryTests.SecureService.WorkerData[] StaffList() {
            return base.Channel.StaffList();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.WorkerData[]> StaffListAsync() {
            return base.Channel.StaffListAsync();
        }
        
        public void ChangeWorkerStatus(string username, DatabaseAndRepositoryTests.SecureService.Status status) {
            base.Channel.ChangeWorkerStatus(username, status);
        }
        
        public System.Threading.Tasks.Task ChangeWorkerStatusAsync(string username, DatabaseAndRepositoryTests.SecureService.Status status) {
            return base.Channel.ChangeWorkerStatusAsync(username, status);
        }
        
        public void SendBugreport(string message, string[] file) {
            base.Channel.SendBugreport(message, file);
        }
        
        public System.Threading.Tasks.Task SendBugreportAsync(string message, string[] file) {
            return base.Channel.SendBugreportAsync(message, file);
        }
        
        public void ChangeWorkerPassWD(string username, string newPassWD) {
            base.Channel.ChangeWorkerPassWD(username, newPassWD);
        }
        
        public System.Threading.Tasks.Task ChangeWorkerPassWDAsync(string username, string newPassWD) {
            return base.Channel.ChangeWorkerPassWDAsync(username, newPassWD);
        }
        
        public void ChangePassWD(string passnewPassWD) {
            base.Channel.ChangePassWD(passnewPassWD);
        }
        
        public System.Threading.Tasks.Task ChangePassWDAsync(string passnewPassWD) {
            return base.Channel.ChangePassWDAsync(passnewPassWD);
        }
        
        public DatabaseAndRepositoryTests.SecureService.WorkerData GetWorker(string username) {
            return base.Channel.GetWorker(username);
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.WorkerData> GetWorkerAsync(string username) {
            return base.Channel.GetWorkerAsync(username);
        }
        
        public DatabaseAndRepositoryTests.SecureService.TechnicianData[] TechnicianList() {
            return base.Channel.TechnicianList();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechnicianData[]> TechnicianListAsync() {
            return base.Channel.TechnicianListAsync();
        }
        
        public DatabaseAndRepositoryTests.SecureService.TechnicianData[] GetAvailableTechnician() {
            return base.Channel.GetAvailableTechnician();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechnicianData[]> GetAvailableTechnicianAsync() {
            return base.Channel.GetAvailableTechnicianAsync();
        }
        
        public void AddNewSolvedQuestion(DatabaseAndRepositoryTests.SecureService.SolvedQuestion solved) {
            base.Channel.AddNewSolvedQuestion(solved);
        }
        
        public System.Threading.Tasks.Task AddNewSolvedQuestionAsync(DatabaseAndRepositoryTests.SecureService.SolvedQuestion solved) {
            return base.Channel.AddNewSolvedQuestionAsync(solved);
        }
        
        public DatabaseAndRepositoryTests.SecureService.SolvedQuestion[] SolvedQuestionList(uint Page) {
            return base.Channel.SolvedQuestionList(Page);
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.SolvedQuestion[]> SolvedQuestionListAsync(uint Page) {
            return base.Channel.SolvedQuestionListAsync(Page);
        }
        
        public DatabaseAndRepositoryTests.SecureService.TechWork[] GetTechWorks() {
            return base.Channel.GetTechWorks();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechWork[]> GetTechWorksAsync() {
            return base.Channel.GetTechWorksAsync();
        }
        
        public DatabaseAndRepositoryTests.SecureService.TechWork[] NewTechWorks() {
            return base.Channel.NewTechWorks();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.TechWork[]> NewTechWorksAsync() {
            return base.Channel.NewTechWorksAsync();
        }
        
        public void ChangeTechnicianStatus(DatabaseAndRepositoryTests.SecureService.TechnicianStatus status) {
            base.Channel.ChangeTechnicianStatus(status);
        }
        
        public System.Threading.Tasks.Task ChangeTechnicianStatusAsync(DatabaseAndRepositoryTests.SecureService.TechnicianStatus status) {
            return base.Channel.ChangeTechnicianStatusAsync(status);
        }
        
        public void RegisterTechWork(DatabaseAndRepositoryTests.SecureService.TechWork work) {
            base.Channel.RegisterTechWork(work);
        }
        
        public System.Threading.Tasks.Task RegisterTechWorkAsync(DatabaseAndRepositoryTests.SecureService.TechWork work) {
            return base.Channel.RegisterTechWorkAsync(work);
        }
        
        public DatabaseAndRepositoryTests.SecureService.CustomerData LastCustomer() {
            return base.Channel.LastCustomer();
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData> LastCustomerAsync() {
            return base.Channel.LastCustomerAsync();
        }
        
        public DatabaseAndRepositoryTests.SecureService.CustomerData GetCustomer(string username) {
            return base.Channel.GetCustomer(username);
        }
        
        public System.Threading.Tasks.Task<DatabaseAndRepositoryTests.SecureService.CustomerData> GetCustomerAsync(string username) {
            return base.Channel.GetCustomerAsync(username);
        }
    }
}
