//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAndRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TechSupportDatabaseEntities : DbContext
    {
        public TechSupportDatabaseEntities()
            : base("name=TechSupportDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<RegUser> RegUser { get; set; }
        public virtual DbSet<SolvedQuestion> SolvedQuestion { get; set; }
        public virtual DbSet<Technician> Technician { get; set; }
        public virtual DbSet<TechWorks> TechWorks { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
