//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegUser()
        {
            this.SolvedQuestion = new HashSet<SolvedQuestion>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public System.DateTime Regtime { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public int Points { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public string Phonenumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolvedQuestion> SolvedQuestion { get; set; }
    }
}
