//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolvedQuestion
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int WorkerID { get; set; }
        public string Question_ { get; set; }
        public string Answer { get; set; }
        public string Category { get; set; }
        public System.DateTime Timeasked { get; set; }
        public System.DateTime Timeanswered { get; set; }
    
        public virtual LoginData LoginData { get; set; }
        public virtual RegUser RegUser { get; set; }
    }
}
