//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAndRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechWorks
    {
        public int ID { get; set; }
        public int TechID { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public int Price { get; set; }
        public string Customername { get; set; }
        public string Customeraddress { get; set; }
    
        public virtual Technician Technician { get; set; }
    }
}
